import "./globals.css"
import Link from "next/link"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
                <nav className="navbar">
                    <ul className="navbar-container">
                        <li>
                            <Link className="nav-link" href="/">
                                Home
                            </Link>
                        </li>
                        <li>
                            <Link className="nav-link" href="/about">
                                About us
                            </Link>
                        </li>
                        <li>
                            <Link className="nav-link" href="/contact">
                                Socials
                            </Link>
                        </li>
                        <li>
                            <Link className="nav-link" href="/zestawy">
                                Zestawy
                            </Link>
                        </li>
                        <li>
                            <Link className="nav-link" href="/food">
                                Food
                            </Link>
                        </li>
                        <li>
                            <Link className="nav-link" href="/napoje">
                                Napoje
                            </Link>
                        </li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    )
}
