import "./globals.css"
import Link from "next/link"
import Image from "next/image"
import {Inter, Dancing_Script} from "next/font/google"
import logo from "../public/logo.svg"
import SearchBar from "@/components/SearchBar/SearchBar"
import Hamburger from "@/components/Hamburger/Hamburger"
import Sidebar from "@/components/Sidebar/Sidebar"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const dancingFont = Dancing_Script({
    weight: ["400", "700"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
})

const inter = Inter({
    weight: ["400", "700"],
    style: ["normal"],
    subsets: ["latin"],
    display: "swap",
})

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="logo">
                    <Link href="/">
                        <Image
                            className="logo-img"
                            src={logo}
                            alt="Logo TanieZarcie.pl"
                        />
                    </Link>
                </div>
                <nav className={dancingFont.className + " navbar"}>
                    <Hamburger>
                        <Sidebar inter={inter} />
                    </Hamburger>
                    <SearchBar />
                </nav>
                <nav
                    style={{
                        fontWeight: 700,
                        fontSize: "clamp(1rem, 1.4vw, 2rem)",
                    }}
                    className={dancingFont.className + " sidebar"}
                >
                    <Sidebar inter={inter} />
                </nav>
                <main className="main">{children}</main>
                <footer>test footer fooooter footer</footer>
            </body>
        </html>
    )
}
